# Site settings
title: Berlin
email: ""
description: "Supporting Asian-owned restaurants and grocers in Berlin"
url: "https://shenchingtou.github.io"
baseurl: "/berlinasianfood"
twitter_username: "shenchingtou"
instagram_username: "thecupandtheroad"
github_username:  "shenchingtou"
share: true

# Owner/author information
owner:
  name:   Athena
  avatar: false
  favicon: false
  info: Berlin Asian Food 

# Settings for comments helper
# Set 'provider' to the comment provider you want to use. (i.e.  Disqus, Intense Debate, livefyre, or Facebook Comments)
# Set 'provider' to false to turn commenting off globally.
#Set 'provider: false' to disable comments globally.
# Disable comments for individual pages/posts by specifying 'comments: false' in the page/post YAML Front Matter.
#
comments :
  provider : false
  disqus :
    short_name : ""

# Internal nav
nav:
  - ABOUT: "https://shenchingtou.github.io/berlinasianfood/"

# All translation keys
translations:
 # 404.html
  permalink: "/404.html"

# Server
destination:      	 ./_site
port:             	 4000


# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# SiteMap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/writing/"
    change_frequency_name: "change_frequency"
    priority_name: "priority"
